### ISSUE TITLE
Feature Request: Support for PreParse field?

### ISSUE THREAD

**Issue by gixxy22** [craft-snippets/Craft-quick-filters#1]
support for the [preparse field](https://github.com/besteadfast/craft-preparse-field) would be great and would allow a many advanced filters to be possible with ease.

**Comment by piotrpog** [comment]
@gixxy22 
thank you for proposal, it is indeed good idea, i will look into that.

**Comment by piotrpog** [comment]
@gixxy22 
Do you have some specific way you would use it in mind?

**Comment by gixxy22** [comment]
Sure, currently i use a preparse field to populate it based on the values of other fields. So some examples would be:

If Field A has content, preparse field would be YES, if not NO, this could then be filtered.

If Field B's content length is 10-20 characters, or 21-30 characters, the preparse field would be updated with the length and filtered.

If (Field C lightswitch is ON AND Field D lightswitch is ON) OR Field E lightswitch is ON, The parse field could be updated to YES/NO, and filtered.

If Field F contains any bad keywords from a list, the preparse field is updated to Good/Bad, Bad could then be filtered and each entry checked.

So many examples where the preparse field could be used with a filter and would make this plugin super useful for finding entries with complexities quickly.

All the conditions would be done in preparse fields, but just need the filter plugin to support the preparse field content.

Thanks

**Comment by piotrpog** [comment]
@gixxy22 
thanks for explaining. Once preparse field plugin gets updated to craft 4, i will try to come up with something.

**Comment by gixxy22** [comment]
hi, is this still a feature you're thinking of adding? thanks

**Comment by piotrpog** [comment]
@gixxy22 yes, it is, i plan to work on that in upcoming month.

**Comment by piotrpog** [comment]
@gixxy22 Hey, i just added support for preparse field with latest version of plugin. Filters based on preparse fields works the same as regular text filters. Is this how you envisioned it?

**Comment by gixxy22** [comment]
hi, great! yes thats opened up a lot of filtering possibilities now, thanks!

is it just for craft 4 or is there a release for C3 too?

**Comment by piotrpog** [comment]
@gixxy22 just for Craft 4 for now. Do you need it for some Craft 3 sites?

**Comment by gixxy22** [comment]
if possible, that would be great! still waiting on many other plugins to be Craft4 compatible before I can upgrade!

**Comment by piotrpog** [comment]
@gixxy22 I will look into that, i never updated plugin for the previous version of Craft while it was already updated to the latest version.

**Comment by piotrpog** [comment]
@gixxy22 
As for now, I do not plan to introduce this change into 3x versions of plugin. Hovewer, you can modify plugin source code yourself, in `models/ElementFilter.php` file.
To do that, you can add `'besteadfast\preparsefield\fields\PreparseFieldType'` to `FIELDS_TEXT` array.
