### ISSUE TITLE
Craft 5

### ISSUE THREAD

**Issue by petehjfd** [craft-snippets/Craft-quick-filters#12]
Hi

I see you have a craft5 branch.  Is there an ETA for a release?

Thanks

**Comment by piotrpog** [comment]
@petehjfd 
Hi,
sorry for the delay with version 5 release. Hope it is not delaying your projects. 
I think i should have it ready around 15th of July.

**Comment by petehjfd** [comment]
Hi @piotrpog 

That's great news, thanks for the quick response!

**Comment by piotrpog** [comment]
@petehjfd 
Hi,
Craft 5 made some changes that block plugin functionality - right now i am waiting for Craft team response if they could restore some specific thing that allows plugin to work.

**Comment by piotrpog** [comment]
@petehjfd 
Hi,
sorry about this large delay - but plguin is updated to craft 5 now. Please note that it requires at least 5.3 version.
