### ISSUE TITLE
Error using 'Dropdown' field

### ISSUE THREAD

**Issue by boudewijn-zicht** [craft-snippets/Craft-quick-filters#3]
An error occurs when we add a filter for a Dropdown field.  This particular Dropdown field is configured with two optgroups.  Part of the callstack is shown below.

Fortunately the fix is quite simple, see https://github.com/craft-snippets/Craft-quick-filters/pull/2

```json
{
  "error": "Undefined index: value",
  "exception": "yii\\base\\ErrorException",
  "file": "/var/www/html/vendor/craftsnippets/craft-quick-filters/src/models/ElementFilter.php",
  "line": 334,
  "trace": [
    {
      "file": "/var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php",
      "line": 84,
      "function": "handleError",
      "class": "yii\\base\\ErrorHandler",
      "type": "->"
    },
    {
      "file": "/var/www/html/vendor/craftsnippets/craft-quick-filters/src/models/ElementFilter.php",
      "line": 334,
      "function": "handleError",
      "class": "craft\\web\\ErrorHandler",
      "type": "->"
    },
}
```

**Comment by piotrpog** [comment]
@boudewijn-zicht thank you for noticing bug and making pull request.
And sorry for the late reaction!

**Comment by boudewijn-zicht** [comment]
> @boudewijn-zicht thank you for noticing bug and making pull request. And sorry for the late reaction!

And thank you for accepting it!
